### ISSUE TITLE
PINTO0309项目使用哪个脚本进行模型转换

### ISSUE THREAD

**Issue by softandhard** [keijiro/YoloV4TinyBarracuda#13]
训练出的权重文件是怎么转换为onnx格式的？

**Comment by keijiro** [comment]
If you're talking about the conversion process, please ask the author of the model. Unfortunately, I don't have any idea about the detailed process.

**Comment by keijiro** [comment]
https://github.com/keijiro/YoloV4TinyBarracuda/issues/14#issue-1966460294

**Comment by keijiro** [comment]
Please click the link on README to see the project.
