### ISSUE TITLE
how to convert onnx

### ISSUE THREAD

**Issue by softandhard** [keijiro/YoloV4TinyBarracuda#14]
you say “This model was converted into ONNX by [PINTO0309](https://github.com/PINTO0309/PINTO_model_zoo) (Katsuya Hyodo)”，Which project should I to choose specifically？

**Comment by keijiro** [comment]
Please use the same thread for the same topic.

**Comment by softandhard** [comment]
> Please use the same thread for the same topic.

do you mean this ：https://github.com/PINTO0309/PINTO_model_zoo/blob/main/115_MoveNet/PINTO_Special/barracuda_gathernd_split/README.md ？

**Comment by keijiro** [comment]
Please use the previous thread, not here.
