### ISSUE TITLE
Can you tell me how to convert the weight file trained by YOLOv4 tiny keras into ONNX format? If you could provide the source code, it would be great

### ISSUE THREAD

**Issue by softandhard** [keijiro/YoloV4TinyBarracuda#15]
When I use the Yolov4 tiny keras project to transform the model, I always cannot use it after importing Unity

**Comment by keijiro** [comment]
Unfortunately, I have no idea about it because I have never trained nor convert YOLO models. I just used pre-converted models.

**Comment by softandhard** [comment]
Can you tell me the address of the pre converted models you are using？
