### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yolov4_tiny_voc.onnx'

### ISSUE THREAD

**Issue by softandhard** [keijiro/YoloV4TinyBarracuda#16]
The above issue occurred when I used Google Colab to transform the model，Excuse me, model yolov4_ Tiny_ Where to obtain voc.onnx？

**Comment by keijiro** [comment]
Sorry, I can't remember exactly where it was. It may be somewhere in [PINTO_model_zoo](https://github.com/PINTO0309/PINTO_model_zoo).
