### ISSUE TITLE
Applicability of onnx model using custom data

### ISSUE THREAD

**Issue by CPT-BJ** [keijiro/YoloV4TinyBarracuda#4]
こんにちは。あなたのGethubを通じてたくさんの勉強をすることができました。 まず、お礼を申し上げます。
一つ質問がありまして、コメントを残させていただきます。

もし他の経路を通じて学習したonnxファイルをあなたのプロジェクトに使えるのか知りたいです。
私は一般的なPASCALVOCファイルの他に私が作ったデータモデルを適用させて該当モデルを修正したいです。

時間を割いて読んでくださってありがとうございます。

Hello, I was able to study a lot through your git hub. First of all, I would like to thank you.
I have a question, so I'm writing to you.

I wonder if I can use the .onnx file that I learned through another route for your project.
In addition to the general PASCALVOC file, I would like to modify the data model that I made by applying it.

Thank you for taking the time to read.

**Comment by keijiro** [comment]
As noted on README, the model file was converted by PINTO0309. Please check his repository for details (actually I don't have good idea about how he converted it).

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/046_yolov4-tiny
