### ISSUE TITLE
using YoloV4Tiny 

### ISSUE THREAD

**Issue by g0983230881** [keijiro/YoloV4TinyBarracuda#6]
When I click play button in every Hierarchy, everything is great.
As I open the Marker IndirectDraw or Visualizer.cs these scripts, then tell me they can't find "YoloV4Tiny "
Did I forget to do something or missing some step? I'm so confused. 
my English is not good, but I try my best to describe my problem and situation.
May you help me in your free time? Thanks!!

![image](https://user-images.githubusercontent.com/54482415/194505142-10f74ed2-afcd-4ea5-907d-82ee9ac5a24c.png)

**Comment by keijiro** [comment]
You can just ignore the error.
